[package]
name    = "interval"
version = "0.1.1"
entry   = "src/lib.vani"
authors = "enthusiasticgeek"
license = "MIT"
registry = "kosh"

[deps]
calculus = { path = "./vendor/calculus", version = "^0.3.0" }
